language: python
python:
  - "2.7"

# command to install dependencies
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq python-numpy python-scipy python-matplotlib ipython ipython-notebook python-pandas python-sympy python-nose
install:
  - "pip install ."

# command to run tests
script: nosetests

notifications:
  email: false